export {homePageController as homePage} from './homePage'
export {getPostController as getPost} from './getPost'
export {storePostController as storePost} from './storePost'
export {newPostController as newPost} from './newPost'
export {registerController as register} from './register'
export {validateRegisterController as validateRegister} from './validateRegister'
export {loginController as login} from './login'
export {validateLoginController as validateLogin} from './validateLogin'
